name: Test formula
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Homebrew/actions/setup-homebrew@main
      - run: brew install arhancanli/tap/arhanpassant
      - run: brew test arhancanli/tap/arhanpassant
      - run: arhanpassant bench
